#!/bin/sh

BASE_PATH=${BASE_PATH:="/"}

sed -i "s|\"API_URL\":.*|\"API_URL\":\"${HOST:=localhost:9000}\"|"  ${CONF_PATH:=/usr/share/www/config.json}
sed -i 's#<base href="\/">#<base href="'"${BASE_PATH}"'">#g' /usr/share/www/index.html

printf "Starting nginx... Egeo Starter should running...\n * App port: 8080\n * Api url:${API_URL} \n"
nginx

echo "Pulling log"
tail -f  /var/log/nginx/access.log
